### PR TITLE
Remove references to ANNOTATION layers for Mapserver 7 compatibility

### PR DESCRIPTION
**Pull request by tchaddad**
Goes with https://github.com/geomoose/geomoose/pull/97

### CODE REVIEW

**Comment by klassenjs** [comment]
Are we sure we want to do this?  My understanding is that #97 and this are more MapServer 7 friendly and will render quicker.  However, I remember something about the polygon layers being split from the annotation so that the labels could appear on top of all the other map-sources drawn, while the polygons were at the bottom of the stack.  However, it doesn't look like that functionality is being used in the demo mapbook (it would require two map-sources pointing to the borders mapfile).

**Comment by tchaddad** [comment]
Your choice - they are currently being rendered together anyways, so the
cartographic behavioir is the same before and after the change.

You could also choose to wait until after Mapserver 7 hits the street, but
that is sounding very close (this week/month?).

>

**Comment by klassenjs** [comment]
Also, MapServer 7 compatibility is important for us on this release as OSGeo Live 9.0 is targeting MapServer 7.  (My comments above are just to make sure we are making a concious decision about merging linework and labels.  Personally, I am in favor of it.

**Comment by klassenjs** [comment]
I combined #97 and #98 and merged into master.
09e7a244653c60f7bb780378d53faf64265e7636

**Pull request closed without merging**
