### PR TITLE
Update version listed in mapbook.xml from 2.6 to 2.8

### PR DESCRIPTION
**Pull request by tchaddad**
Somehow we missed this last time...

### CODE REVIEW

**Comment by elil** [comment]
We should update the process too... https://github.com/geomoose/geomoose-website/blob/master/source/developer/release.rst

**Comment by klassenjs** [comment]
I'm not sure if we should do this every release or not (although I agree
it is warranted for this release).

My understanding is the reason for having the version attribute in the
mapbook is so that we can potentially support older mapbooks with newer
GeoMoose releases (by invoking a compatibility mapbook parser).  But
that also means we should only update the version in the mapbook when it
has been changed so that it doesn't apply to older versions anymore.

On the other hand, a new x.y release (by semantic versioning)  is likely
to have new features that are added to the demo which would mean a
mapbook change, so this might be moot.

Thoughts?

**Comment by klassenjs** [comment]
I do think we should stick to x.y versions (not x.y.z) in the mapbook as we aren't supposed to be introducing features or breaking changes in the .z bugfix releases.

**Comment by tchaddad** [comment]
Yeah - I wondered about that too. It's just that it is a bit confusing to users that our Mapbook numbering is so similar to our overall version numbering. I could see us having much lower numbers for Mapbook versions than for Geomoose versions (since Mapbook versions change less frequently). 

I just happened to notice this today, and assumed it was an oversight as there are a few new Mapbook elements in 2.8 (related to popups) that wouldn't work in earlier versions if someone tried.

**Comment by tchaddad** [comment]
Agree with your x.y comment

**Comment by elil** [comment]
I agree sticking to x.y (and not x.y.z).

For updating the process, we can add something to the effect, `evaluate  <mapbook version="#.#">` so that it doesn't get overlooked or incremented for no reason.

**Comment by klassenjs** [comment]
+1

**Pull request merged**
